
language: android


android:
  components:
    - build-tools-29.0.2
    - android-15
    - android-22
    - android-28
    - tools
    - platform-tools
    - add-on
    - extra
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
# Images
    - sys-img-armeabi-v7a-android-22
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

notifications:
  email: true

env:
  matrix:
    - ANDROID_TARGET=google_apis-25  ANDROID_ABI=armeabi-v7a

  global:
    - ADB_INSTALL_TIMEOUT=20



before_install:
  - chmod +x gradlew


before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - ./gradlew build connectedCheck
  - ./gradlew connectedAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)