language: android
jdk: oraclejdk8
sudo: required

env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
  - android-25
  - android-24
  - android-23
  - android-22
  - android-21
  - android-20
  - android-19
  - android-18
  - android-17
  - android-16
  - android-15

notifications:
  email: true

before_script:
  - android-wait-for-emulator

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew build connectedCheck
  - ./gradlew connectedAndroidTest

after_success:
  - bash <(curl -s https://codecov.io/bash)
